apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-master-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.240.0.3
    path: /exports/spark-master

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spark-master-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi