apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: spark-master
          imagePullPolicy: Always
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 1
          volumeMounts:
            - name: spark-master
              mountPath: /spark-master
          env:
            - name: SPARK_PUBLIC_DNS
              value: 'spark.labs.uninett.no'
      volumes:
        - name: spark-master
          persistentVolumeClaim:
            claimName: spark-master
